- name: control host setup playbook
  hosts: local
  become: yes
  tasks:
  - name: system update
    apt:
      upgrade: yes
      update_cache: yes
  - name: package installation
    apt:
      name:
      - emacs-nox
      - elpa-yaml-mode
      - tmux
      - python-is-python3
      state: present
  - name: set control node hostname
    ansible.builtin.hostname:
      name: control